name: sinalverde
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/microfone.png
  - assets/sinal.png
  - assets/apr.mp3
  - assets/cnx.mp3
  - assets/espera.mp3
  - assets/sinalverde.mp3
  - assets/sinalvermelho.mp3

flutter_icons:
  android: true
  ios: true
